import json
import os
import threading
import uuid
from datetime import datetime

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from pydantic import BaseModel
from sqlalchemy import Column, DateTime, String, Text, create_engine
from sqlalchemy.orm import declarative_base, sessionmaker

# == Load Environment Variables ==
load_dotenv()  # Load environment from the env file
database_url = os.getenv("DATABASE_URL")  # get the database url

if not database_url:
    raise RuntimeError("DATABASE_URL environment variable is not set.")

# Fix for Heroku's postgres:// URL format
if database_url.startswith("postgres://"):
    database_url = database_url.replace("postgres://", "postgresql://", 1)

# Db setup
Base = declarative_base()
engine = create_engine(database_url, echo=False)  # create the engine to connect to the database
SessionLocal = sessionmaker(bind=engine)  # create a session maker to manage the session with the database

# Check database connection before starting
try:
    with engine.connect() as conn:
        print("Database connection OK")
except Exception as e:
    raise RuntimeError(f"Database connection failed: {e}")

from src.planning_agent import planning_agent


class Task(Base):
    __tablename__ = "tasks"
    id = Column(String, primary_key=True, index=True)
    prompt = Column(Text)
    status = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow)
    result = Column(Text)


try:
    # Drop all tables
    Base.metadata.drop_all(bind=engine)
except Exception as e:
    print(f"Error dropping tables: {e}")


try:
    # Create all tables
    Base.metadata.create_all(bind=engine)
except Exception as e:
    print(f"Error creating tables: {e}")


# Fast Api setup
app = FastAPI(title="Agentic AI", description="An AI agent that can perform tasks based on user prompts.", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"]
)

app.mount("/static" , StaticFiles(directory="static"), name="static")


# It performs the task of rendering HTML templates using Jinja2. It specifies the directory where the templates are located, allowing the application to serve dynamic HTML content based on the tempaltes and data provided by the backend logic.This is useful for creating web pages that can display data, forms, or other dynamic content generated by the FastAPI application.
templates = Jinja2Templates(directory='templates')


task_progress = {}

class PromptRequest(BaseModel):
    prompt: str

# Now Create the Apis
@app.get("/", response_class=HTMLResponse)
def read_index(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})


# Health check endpoint
@app.get("/health" , response_class=JSONResponse)
def health_check():
    return {"status": "ok"}


# Generate Report
@app.post("/generate_report")
def generate_report(request: PromptRequest):
    task_id = str(uuid.uuid4())
    db = SessionLocal()
    db.add(Task(id=task_id, prompt=request.prompt, status="running"))
    db.commit()
    db.close()

    task_progress[task_id] = {"steps": []}
    initial_plan_steps = planning_agent(request.prompt)
    print(f"Planning agent returned: {initial_plan_steps}")

    # initial plan give the steps
    for step_title in initial_plan_steps:
        task_progress[task_id]["steps"].append({
            "title": step_title,
            "status": "pending",
            "description": "awaiting execution",
            "substeps": []
        })

    thread = threading.Thread(target=run_agent_workflow, args=(task_id, request.prompt, initial_plan_steps))
    thread.start()

    return {"task_id": task_id}


# Now the task is done in the backend
# User can get the task progress of the task by using the task_id
@app.get("/task_progress/{task_id}")
def get_task_progress(task_id: str):
    return task_progress.get(task_id, {"steps": []})


# Now get the task result by using the task_id
@app.get("/task_status/{task_id}")
def get_task_result(task_id: str):
    db = SessionLocal()
    task = db.query(Task).filter(Task.id == task_id).first()
    db.close()

    if not task:
        raise HTTPException(status_code=404, detail="Task not found")

    return {
        "status": task.status,
        "result": json.loads(task.result) if task.result else None,
    }


def run_agent_workflow(task_id: str, prompt: str, initial_plan_steps: list):
    steps_data = task_progress[task_id]["steps"]
    execution_history = []

    def update_step_status(index: int , status: str , description: str = None, substeps: list = None):
        steps_data[index]["status"] = status
        if description:
            steps_data[index]["description"] = description
        if substeps is not None:
            steps_data[index]["substeps"].append(substeps)
        steps_data[index]["updated_at"] = datetime.utcnow().isoformat()


    # Now execute the steps one by one 
    for i , step_title in enumerate(initial_plan_steps):
        update_step_status(i , "running", f"Executing step: {step_title}")
        

        # Now each step we have to send the current step_title to execute
        # and the previous steps execution history
        # and the user prompt to the executor agent to get the result of the current step
        actual_step_description , agent_name , output = executor_agent_step(step_title , execution_history , prompt)

        execution_history.append([step_title, actual_step_description, output])

























